when@never:
    _anchors:
        openai_base: &openai_base
            source: 'openAi'
            apiKey: '%env(OPENAI_API_KEY)%'
        openai_large: &openai_large
            <<: *openai_base
            model: 'text-embedding-3-large'
        openai_small: &openai_small
            <<: *openai_base
            model: 'text-embedding-3-small'

survos_meili:
    host: '%env(default::MEILI_SERVER)%'
    apiKey: '%env(default::MEILI_API_KEY)%'
    searchKey: '%env(default::MEILI_SEARCH_KEY)%'
    multiLingual: false
    translationStyle: off # off, simple/key, compound (label/info)?  per-index? do we need a translation domain?

    chat:
        workspaces:
            meili_assistant:
                source: openAi
                apiKey: '%env(OPENAI_API_KEY)%'
                model: gpt-4o-mini
                label: Product Catalog
                detailUrlPattern: '/product/{id}'
                examples:
                    - cheapest wireless headphones
                    - gifts for a tech executive under $50
                    - highly rated kitchen appliances
                    - blue running shoes in stock

    embedders:
        product:
            <<: *openai_large
            template: 'templates/liquid/product.liquid'
            examples:
                - cool gifts for a tech executive
                - things to decorate an apartment
        wam:
            <<: *openai_large
            template: 'templates/liquid/wam.liquid'
            examples:
                - animals
        marvel:
            <<: *openai_large
            template: 'templates/liquid/marvel.liquid'
            examples:
                - animals
        amst_en_large:
            <<: *openai_large
            template: 'templates/liquid/amst.liquid'
        amst_en_small:
            <<: *openai_small
            template: 'templates/liquid/amst.liquid'
